apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mollysocket.fullname" . }}
  labels:
    {{- include "mollysocket.labels" . | nindent 4 }}
  annotations:
    configmap-hash: {{ .Values.mollysocket | toYaml | sha256sum }}
data:
  molly.toml: |-
    environment = "{{ .Values.mollysocket.environment }}"
    allowed_uuids = {{ .Values.mollysocket.allowedUUIDs | toJson }}
    allowed_endpoints = {{ .Values.mollysocket.allowedEnpoints | toJson }}
    db = "/database/molly.sqlite"
