---
{{- $fullname := include "mollysocket.fullname" . }}
{{- $vapidKey := .Values.mollysocket.vapidKey.key }}
{{- with (lookup "v1" "Secret" .Release.Namespace $fullname) }}
{{- with get . "data" }}
{{- $vapidKey = $vapidKey | default (get . "ms_vapid_key" | b64dec) }}
{{- end }}
{{- end }}


apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}
  annotations:
    "helm.sh/hook": pre-install
    helm.sh/resource-policy: keep
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "mollysocket.labels" . | nindent 4 }}
data:
  {{- with $vapidKey }}
  ms_vapid_key: {{ . | b64enc }}
  {{- end }}
