{{- if and
  .Values.persistence.enabled
  (not .Values.persistence.hostPath)
  (not .Values.persistence.existingClaim)
}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "ocrserver.fullname" . }}
  labels:
    {{- include "ocrserver.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-failed
    {{- with .Values.persistence.annotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- with .Values.persistence.storageClass }}
  {{-  if (eq "-" .) }}
  storageClassName: ""
  {{-  else }}
  storageClassName: {{ . | quote }}
  {{-  end }}
  {{- end }}
{{- end -}}
