{
 "title": "ntfy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Published",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ntfy_messages_published_success",
     "legendFormat": "Messages cached"
    }
   ]
  },
  {
   "title": "Cached",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ntfy_messages_cached_total", "legendFormat": "Messages cached" }
   ]
  },
  {
   "title": "Visitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ntfy_visitors_total", "legendFormat": "Visitors" }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ntfy_users_total", "legendFormat": "Visitors" }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ntfy_topics_total", "legendFormat": "Topics" }
   ]
  },
  {
   "title": "Subscribers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ntfy_subscribers_total", "legendFormat": "Subscribers" }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Messages published",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "ntfy_messages_published_success",
     "legendFormat": "Successful"
    },
    {
     "expr": "ntfy_messages_published_failure",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Visitors, subscribers, topics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "targets": [
    { "expr": "ntfy_visitors_total", "legendFormat": "Visitors" },
    { "expr": "ntfy_topics_total", "legendFormat": "Topics" },
    { "expr": "ntfy_subscribers_total", "legendFormat": "Subscribers" },
    { "expr": "ntfy_users_total", "legendFormat": "Users" }
   ]
  },
  {
   "title": "HTTP responses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "ntfy_http_requests_total",
     "legendFormat": "{{http_method}} {{http_code}} {{ntfy_code}}"
    }
   ]
  },
  {
   "title": "HTTP responses (HTTP code only)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "sum by(http_code) (ntfy_http_requests_total)",
     "legendFormat": "{{http_code}}"
    }
   ]
  },
  {
   "title": "Messages cached",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "targets": [
    { "expr": "ntfy_messages_cached_total", "legendFormat": "Messages in database" }
   ]
  },
  {
   "title": "Attachments: Total cache size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "ntfy_attachments_total_size", "legendFormat": "Total size in MB" }
   ]
  },
  {
   "title": "Matrix messages published",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "targets": [
    { "expr": "ntfy_matrix_published_success", "legendFormat": "Success" },
    { "expr": "ntfy_matrix_published_failure", "legendFormat": "Failure" }
   ]
  },
  {
   "title": "UnifiedPush messages published",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "ntfy_unifiedpush_published_success",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Emails sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "targets": [
    { "expr": "ntfy_emails_sent_success", "legendFormat": "Successful" },
    { "expr": "ntfy_emails_sent_failure", "legendFormat": "Failure" }
   ]
  },
  {
   "title": "Emails received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "targets": [
    { "expr": "ntfy_emails_received_success", "legendFormat": "Success" },
    { "expr": "ntfy_emails_received_failure", "legendFormat": "Failure" }
   ]
  },
  {
   "title": "Firebase messages sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "ntfy_firebase_published_success",
     "legendFormat": "Success"
    },
    {
     "expr": "ntfy_firebase_published_failure",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Message publish duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ntfy_message_publish_duration_ms",
     "legendFormat": "Duration"
    }
   ]
  },
  { "title": "Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Go routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"ntfy\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}