{
 "title": "Autopush: Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(statsd_exporter_build_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Push", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Notification Message",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(autopush_notification_message_retrieved{namespace=~\"$namespace\"}[$__range])) without (container,endpoint,instance,pod,job,service)",
     "legendFormat": "Retrieved: {{namespace}}"
    },
    {
     "expr": "sum(increase(autopush_notification_message_deleted{namespace=~\"$namespace\"}[$__range])) without (container,endpoint,instance,pod,job,service)",
     "legendFormat": "Deleted: {{namespace}}"
    }
   ]
  },
  {
   "title": "UA Notify Send",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(autopush_ua_notification_sent{namespace=~\"$namespace\"}[$__range])) without (container,endpoint,instance,pod,job,service)",
     "legendFormat": "OS: {{namespace}}/{{os}}"
    }
   ]
  },
  { "title": "Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "No Subscription API Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(autoendpoint_api_error_no_subscription{namespace=~\"$namespace\"}[$__range])) without(container,endpoint,instance,pod,service,job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}