{{- if .Values.prometheus.podmonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
    {{- with .Values.prometheus.podmonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: home-assistant
  podMetricsEndpoints:
    - port: http
      path: "/api/prometheus"
      bearerTokenSecret:
        {{- toYaml .Values.prometheus.podmonitor.bearerTokenSecret | nindent 8 }}
{{- end }}
