apiVersion: v2
name: forgejo-runner
description: Deploy runner for an forgejo instance (default codeberg.org)
type: application
version: "0.4.12"
# renovate: image=code.forgejo.org/forgejo/runner
appVersion: "6.2.1"
maintainers:
  - name: WrenIX
    url: https://wrenix.eu
