{{- if and .Values.persistence.enabled ( not .Values.persistence.existingClaim) -}}
---
{{- if .Values.persistence.hostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "ntfy.fullname" . }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
  {{- if .Values.persistence.annotations }}
  annotations:
    {{ toYaml .Values.persistence.annotations | indent 4 }}
  {{- end }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  hostPath:
    path: "{{ .Values.persistence.hostPath }}"
---
{{- end }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "ntfy.fullname" . }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
  {{- if .Values.persistence.annotations }}
  annotations:
    {{ toYaml .Values.persistence.annotations | indent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  {{- if .Values.persistence.hostPath }}
  volumeName: {{ template "ntfy.fullname" . }}
  {{- end }}
{{- end -}}
