---
{{- $fullname := include "ntfy.fullname" . }}
{{- $secretName := printf "%s-env" $fullname }}
{{- $public := .Values.ntfy.webPush.keys.public }}
{{- $private := .Values.ntfy.webPush.keys.private }}

{{- with (lookup "v1" "Secret" .Release.Namespace $secretName)}}
{{- with get . "data" }}
{{- $public = $public | default (get . "NTFY_WEB_PUSH_PUBLIC_KEY" | b64dec) }}
{{- $private = $private | default (get . "NTFY_WEB_PUSH_PRIVATE_KEY" | b64dec) }}
{{- end }}
{{- end }}


apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    helm.sh/resource-policy: keep
    confighash: {{ .Values.ntfy | toYaml | sha256sum | trunc 32 }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
data:

  # web-push
  {{- with $public }}
  NTFY_WEB_PUSH_PUBLIC_KEY: {{ . | b64enc }}
  {{- end }}
  {{- with $private }}
  NTFY_WEB_PUSH_PRIVATE_KEY: {{ . | b64enc }}
  {{- end }}
