---
apiVersion: v2
name: matrix-authentication-service
description: OAuth2.0 + OpenID Provider for Matrix Homeservers (per MSC3861)
icon: https://matrix.org/images/matrix-logo.svg
type: application
version: "0.0.12"
# renovate: image=ghcr.io/element-hq/matrix-authentication-service
appVersion: "0.16.0-rc.0"
maintainers:
  - name: WrenIX
    url: https://wrenix.eu
