{{- with .Values.gotosocial.metrics.auth }}
{{- if and $.Values.gotosocial.metrics.enabled .enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gotosocial.fullname" $ }}-metrics-auth
  labels:
    {{- include "gotosocial.labels" $ | nindent 4 }}
  annotations:
    "confighash.metrics-auth": {{ toYaml . | sha256sum | trunc 32 }}
data:
  GTS_METRICS_AUTH_ENABLED: {{ "true" | b64enc }}
  GTS_METRICS_AUTH_USERNAME: {{ .username | b64enc }}
  GTS_METRICS_AUTH_PASSWORD: {{ .password | b64enc }}
{{- end }}{{/* end-if .enabled */}}
{{- end }}{{/* end-with .gotosocial.metrics.auth */}}
