{{- if .Values.mollysocket.vapidKey.create }}
---
{{- $fullname := (include "mollysocket.fullname" .) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullname }}-setup
  labels:
    {{- include "mollysocket.labels" . | nindent 4 }}
    app.kubernetes.io/component: setup-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - {{ $fullname }}
    verbs:
      - get
      - update
      - patch
{{- end }}
