---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager-matrix.fullname" . }}
  annotations:
    config-icons: {{ toYaml .Values.bot.icons | sha256sum }}
    config-colors: {{ toYaml .Values.bot.colors | sha256sum }}
    config-templates: {{ toYaml .Values.bot.template | sha256sum }}
data:
  icon.yaml: |
    {{- toYaml .Values.bot.icons  | nindent 4 }}
  color.yaml: | 
    {{- toYaml .Values.bot.colors | nindent 4 }}
  text.tpl: |
    {{- .Values.bot.template.text | nindent 4 }}
  html.tpl: |
    {{- .Values.bot.template.html | nindent 4 }}
