apiVersion: v2
name: home-assistant
description: Home Assistant with tooling to run on an k3s pi
icon: https://www.home-assistant.io/images/favicon-192x192.png
type: application
version: 0.2.10
# renovate: image=ghcr.io/home-assistant/home-assistant
appVersion: "2024.12.2"
maintainers:
  - name: WrenIX
    url: https://wrenix.eu
