apiVersion: v2
name: home-assistant
description: Home Assistant with tooling to run on an k3s pi
type: application
version: 0.1.0
appVersion: "2024.3.1"
maintainers:
  - name: WrenIX
    url: https://wrenix.eu
