---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "element-call.fullname" . }}
  labels:
    {{- include "element-call.labels" . | nindent 4 }}
data:
  "config.json": |
    {{- toJson .Values.service.call.config | nindent 4 }} 
