---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headscale.fullname" . }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    config-hash: {{ toYaml .Values.headscale.config | sha256sum | trunc 32 }}
type: Opaque
stringData:
  config.yaml: |
    {{- toYaml .Values.headscale.config | nindent 4 }}
