{{- if (.Capabilities.APIVersions.Has "traefik.io/v1alpha1/ServersTransport") }}
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ include "headscale.fullname" . }}
spec:
    serverName: {{ .Values.headscale.certmanager.dnsNames | first }}
{{- end }}
