{{- if .Values.zigbee2mqtt.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}-zigbee2mqtt
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
    type: zigbee2mqtt
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
{{- end }}
