apiVersion: v2
name: paperless-ngx
description: A document management system that transforms your physical documents into a searchable online archive so you can keep, well, less paper.
type: application
icon: https://github.com/paperless-ngx/paperless-ngx/raw/main/resources/logo/web/svg/square.svg
home: https://wrenix.eu/docs/helm-charts/paperless-ngx/
version: "0.1.9"
# renovate: image=ghcr.io/paperless-ngx/paperless-ngx
appVersion: "2.15.1"
keywords:
  - paperless
  - paperless-ng
  - paperless-ngx
  - dms
  - document
maintainers:
  - name: WrenIX
    url: https://wrenix.eu
sources:
  - https://github.com/paperless-ngx/paperless-ngx
  - https://git.chaos.fyi/wrenix/helm-charts/src/branch/main/paperless-ngx
  - https://codeberg.org/wrenix/helm-charts/src/branch/main/paperless-ngx
dependencies:
  - name: postgresql
    version: "^16.5.6"
    repository: "oci://docker.io/bitnamicharts"
    condition: postgresql.enabled
  - name: redis
    version: "20.11.5"
    repository: "oci://docker.io/bitnamicharts"
    condition: redis.enabled
