{{- if .Values.ntfy.webPush.keys.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ntfy.fullname" . }}-setup
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
    app.kubernetes.io/component: setup-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- end }}
