{{- if and .Values.prometheus.rules.enabled }}
---
{{- $fullname := include "pretix.fullname" . }}
{{- $filter := printf `namespace="%s",job="%s"` .Release.Namespace $fullname }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "pretix.labels" . | nindent 4 }}
    {{- with .Values.prometheus.rules.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ $fullname }}-Default
      rules:
        - alert: "pretix: error in task"
          expr: rate(pretix_task_runs_total{status!="success", {{ $filter }} }[1h])!=0
          for: 5m
          labels:
            severity: critical
          annotations:
            {{`
            summary: "pretix task of {{ $labels.instance }} has an error on {{ $labels.task_name }} in the last hour"
            `}}
    {{- with .Values.prometheus.rules.additionalRules }}
    - name: {{ $fullname }}-Additional
      rules:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
