---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pretix.fullname" . }}
  labels:
    {{- include "pretix.labels" . | nindent 4 }}
  annotations:
    checksum/secret: {{ toYaml $.Values.env | sha256sum }}
data:
  {{- range $name, $value := .Values.env }}
  {{ $name }}: {{ toYaml $value | b64enc }}
  {{- end }}
