apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hydrogen-web.fullname" . }}-config
  annotations:
    confighash: {{ .Values.hydrogen | toYaml | sha256sum | trunc 32 }}
  labels:
    {{- include "hydrogen-web.labels" . | nindent 4 }}
data:
  config.json: |-
    {{- toJson .Values.hydrogen | nindent 4}}