apiVersion: v2
name: alertmanager-ntfy
description: Receiver for alertmanager to forward to ntfy.sh
type: application
version: "0.1.7"
# renovate: image=codeberg.org/xenrox/ntfy-alertmanager
appVersion: "0.4.0"
maintainers:
  - name: WrenIX
    url: https://wrenix.eu
