apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale-ui.fullname" . }}
  labels:
    {{- include "headscale-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.https }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "headscale-ui.selectorLabels" . | nindent 4 }}
