{{- $secretName := include "matrix-sliding-sync.fullname" . }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "matrix-sliding-sync.labels" . | nindent 4 }}
data:
  SYNCV3_SERVER: {{ .Values.config.homeserver | b64enc }}
  {{- with .Values.config.postgresql }}
  SYNCV3_DB: {{ (printf "postgresql://%s:%s@%s:%v/%s?sslmode=%s"
                   .username
                   .password
                   .host
                   .port
                   .database
                   .sslmode
                ) | b64enc }}
  {{- end }}
  SYNCV3_SECRET: {{ .Values.config.syncSecret
    | default (dig "data" "SYNCV3_SECRET" "" $secret | b64dec)
    | default (randAlphaNum 64)
    | b64enc
  }}
  SYNCV3_BINDADDR: {{ printf ":%v" .Values.service.port | b64enc }}
  {{- with .Values.config.metrics }}
  SYNCV3_PROM: {{ printf ":%v" . | b64enc }}
  {{- end }}
  {{- with .Values.config.opentelemetry }}
  {{- with .url }}
  SYNCV3_OTLP_URL: {{ . | b64enc }}
  {{- end }}
  {{- with .username }}
  SYNCV3_OTLP_USERNAME: {{ . | b64enc }}
  {{- end }}
  {{- with .password }}
  SYNCV3_OTLP_PASSWORD: {{ . | b64enc }}
  {{- end }}
  {{- end }}
  SYNCV3_LOG_LEVEL: {{ .Values.config.logLevel | b64enc }}
  SYNCV3_MAX_DB_CONN: {{ toString .Values.config.postgresql.maxConn | b64enc }}
