{{- range $prober := $.Values.prober }}
{{- range $probe := $.Values.probes }}
{{- range $groupName, $group := $probe.groups }}
{{- $proto := "ipv4" }}
{{- range $proto := (list "ipv4" "ipv6") }}
{{- if (get $probe $proto) }}
---
apiVersion: monitoring.coreos.com/v1 
kind: Probe
metadata:
  name: {{ $probe.name }}-{{ $groupName }}-{{ $proto }}-{{ $prober.name }}
  labels:
    {{- toYaml $.Values.prometheus.probe.labels | nindent 4 }}
spec:
  prober:
    {{- toYaml $prober.spec | nindent 4}}
  module: "{{ $probe.module }}_{{ $proto }}"
  targets:
    staticConfig:
      labels:
        group: {{ $groupName }} 
        probe: {{ $probe.name }}
        prober: {{ $prober.name }}
      static:
        {{- toYaml $group | nindent 8 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
