---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stalwart-mail.fullname" . }}-env
  labels:
    {{- include "stalwart-mail.labels" . | nindent 4 }}
    app.kubernetes.io/component: main
data:
  {{- range $key, $value := .Values.secrets.env }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
