---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stalwart-mail.fullname" . }}
  labels:
    {{- include "stalwart-mail.labels" . | nindent 4 }}
  annotations:
    confighash: {{ toYaml .Values.config | sha256sum | trunc 32 }}
data:
  "config.toml": {{ regexReplaceAll
    "trusted-networks = \\[(.*)\\]"
    (
      toToml .Values.config
      | replace ".0\n" "\n"
      | replace "fts-table-duplicated-workaround" "fts"
    )
    "trusted-networks = {${1}}"
    | b64enc }}
  "dkim.key": {{ genPrivateKey "rsa" | b64enc }}
