{
 "title": "Speedtest-Exporter Dashboard",
 "description": "Dashboard for Speedtest Exporter https://github.com/MiguelNdeCarvalho/speedtest-exporter",
 "tags": [ "network" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(speedtest_up, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status of the Speedtest-Exporter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_up{job=~\"$job\"}) without (instance,pod)"
    }
   ]
  },
  {
   "title": "ServerID (Last test done)",
   "type": "stat",
   "description": "ServerID of the last test done",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_server_id{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Gauges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Download Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_download_bits_per_second{job=~\"$job\"}) without (instance,pod)"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_upload_bits_per_second{job=~\"$job\"}) without (instance,pod)"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(speedtest_ping_latency_milliseconds{job=~\"$job\"}) without (instance,pod)"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(speedtest_jitter_latency_milliseconds{job=~\"$job\"}) without (instance,pod)"
    }
   ]
  },
  {
   "title": "Graphics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(speedtest_download_bits_per_second{job=~\"$job\"}) without (instance,pod)",
     "legendFormat": "Download: {{ instance }}"
    },
    {
     "expr": "sum(speedtest_upload_bits_per_second{job=~\"$job\"}) without (instance,pod)",
     "legendFormat": "Upload: {{ instance }}"
    }
   ]
  },
  {
   "title": "Ping and Jitter (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(speedtest_ping_latency_milliseconds{job=~\"$job\"}) without (instance,pod)",
     "legendFormat": "Ping (ms)"
    },
    {
     "expr": "avg(speedtest_jitter_latency_milliseconds{job=~\"$job\"}) without (instance,pod)",
     "legendFormat": "Jitter (ms)"
    }
   ]
  }
 ]
}