apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mautrix-signal.fullname" . }}
  labels:
    {{- include "mautrix-signal.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mautrix-signal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        "checksum/secret": {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "mautrix-signal.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mautrix-signal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.image }}
          image: "{{ coalesce $.Values.global.image.registry .registry }}/{{ .repository }}:{{ .tag | default (printf "v%s" $.Chart.AppVersion) }}"
          imagePullPolicy: {{ coalesce $.Values.global.image.pullPolicy .pullPolicy }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.config.appservice.port }}
              protocol: TCP
            {{- if .Values.config.metrics.enabled }}
            - name: metrics
              containerPort: {{ regexSplit ":" .Values.config.metrics.listen -1 | last  }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /data/config.yaml
              subPath: config.yaml
            - name: config
              mountPath: /data/registration.yaml
              subPath: registration.yaml
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "mautrix-signal.fullname" . }}
            items:
              - key: config.yaml
                path: config.yaml
              - key: registration.yaml
                path: registration.yaml
        - name: "data"
          {{- if .Values.persistence.enabled }}
          {{- if .Values.persistence.hostPath }}
          hostPath:
            type: Directory
            path: {{ .Values.persistence.hostPath | quote }}
          {{- else }}{{/* else .persistence.hostPath */}}
          persistentVolumeClaim:
            claimName: {{ coalesce .Values.persistence.existingClaim (include "mautrix-signal.fullname" .) }}
          {{- end }}{{/* end-else .persistence.hostPath */}}
          {{- else }}{{/* else .persistence.enabled */}}
          emptyDir: {}
          {{- end }}{{/* end-else .persistence.enabled */}}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
