---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  user: {{ .Values.postgres.user | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
