---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forgejo-runner.fullname" . }}-configfile
  labels:
    {{- include "forgejo-runner.labels" . | nindent 4 }}
  annotations:
    config-hash: {{ toYaml .Values.runner.config.file | sha256sum }}
    "helm.sh/hook": "pre-install,pre-upgrade"
data:
  config.yaml: {{ toYaml .Values.runner.config.file | b64enc }}
