{{- $secretName := include "matrix-authentication-service.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "matrix-authentication-service.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- .Values.config | nindent 4 }}
