{{- if .Values.prometheus.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "matrix-authentication-service.fullname" . }}
  labels:
    {{- include "matrix-authentication-service.labels" . | nindent 4 }}
    {{- with .Values.prometheus.servicemonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "matrix-authentication-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: "/metrics"
{{- end }}
