---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-ntfy.fullname" . }}
  annotations:
    confighash: {{ .Values.ntfyAlertmanager | toYaml | sha256sum | trunc 32 }}
  labels:
    {{- include "alertmanager-ntfy.labels" . | nindent 4 }}
stringData:
  {{- with .Values.ntfyAlertmanager }}
  config: |
    http-address :{{ .port }}
    log-level {{ .logLevel }}
    {{- if not (empty .password) }}
    user {{ .user }}
    password {{ .password }}
    {{- end }}
    {{- with .ntfy }}
    ntfy {
      topic {{ .topic }}
      {{- if not (empty .password) }}
      user {{ .user }}
      password {{ .password }}
      {{- end }}
    }
    {{- end }}
    {{- with .labels }}
    labels {
      order {{ .order | join "," | quote }}

      {{- range .entries }}
      {{ .label }} {{ .value | quote }} {
        {{- with .priority }}
        priority {{ . }}
        {{- end }}
        {{- with .tags }}
        tags {{ . | join "," | quote }}
        {{- end }}
      }

      {{- end }}
    }
    {{- end }}
    {{- with .resolved }}
    resolved {
        {{- with .tags }}
        tags {{ . | join "," | quote }}
        {{- end }}
    }
    {{- end }}
    {{- end }}
