FROM python:3.13-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install any needed packages
RUN pip install -r requirements.txt

# Copy the application code into the container
COPY setup.py setup.py

CMD ["python", "setup.py"]
